version: "3.8"

services:
  backend:
    image: php:8.2-fpm
    container_name: sigcon-backend
    volumes:
      - ./backend:/var/www/html
    working_dir: /var/www/html

  frontend:
    image: node:18
    container_name: sigcon-frontend
    volumes:
      - ./frontend:/app
    working_dir: /app
