services:
  backend:
    ports:
      -"8000:8000"
    build:
      context: ./docker/php
    container_name: backend
    volumes:
      - ./backend:/var/www/html
    working_dir: /var/www/html
    networks:
      - sigcon

  nginx:
    image: nginx:stable
    container_name: sigcon-nginx
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - sigcon

  db:
    image: postgres:15
    container_name: sigcon-db
    environment:
      POSTGRES_DB: sigcon
      POSTGRES_USER: sigcon
      POSTGRES_PASSWORD: sigcon
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - sigcon

networks:
  sigcon:

volumes:
  db_data:
